jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Run java checkstyle
      uses: nikitasavinov/checkstyle-action@0.5.1
      with:
        checkstyle_config: ./.github/workflows/checks_rules.xml
        checkstyle_version: '8.32'
        fail_on_error: false
        level: error
        reporter: github-pr-check
name: CheckStyle
on:
  repository_dispatch:
    types: trigger-ga___checkstyle.yml
