jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      id: cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
        path: '/opt/hostedtoolcache/z3

          /opt/hostedtoolcache/ghidra

          '
    - continue-on-error: true
      if: steps.cache.outputs.cache-hit != 'true'
      name: Setup Ghidra
      uses: er28-0652/setup-ghidra@0.0.6
      with:
        version: '10.4'
    - continue-on-error: true
      if: steps.cache.outputs.cache-hit != 'true'
      name: Download Z3
      uses: pavpanchekha/setup-z3@0.2.0
      with:
        architecture: x64
        distribution: glibc-2.31
        version: 4.8.15
    - continue-on-error: true
      if: steps.cache.outputs.cache-hit == 'true'
      name: Setup Environment variables if use cache
      run: 'echo "CPATH=/opt/hostedtoolcache/z3/4.8.15/x64/z3-4.8.15-x64-glibc-2.31/include"
        >> $GITHUB_ENV

        echo "GHIDRA_INSTALL_DIR=/opt/hostedtoolcache/ghidra/10.4/x64" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Setup Z3
      run: 'cp $CPATH/../bin/com.microsoft.z3.jar $GITHUB_WORKSPACE/lib/com.microsoft.z3.jar

        sudo cp $CPATH/../bin/*.so  /lib

        '
    - continue-on-error: true
      name: Unit test
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: test
        gradle-version: 7.4
name: Unit test
on:
  repository_dispatch:
    types: trigger-ga___unittest.yml
